atlas_org_id = "var.atlas_org_id"
atlas_project_name = "lighten"
environment = "dev"
cluster_instance_size_name = "M0"
cloud_provider = "AWS"
atlas_region = "US_EAST_1"
mongodb_version = "6.0"
ip_address = "38.95.248.86"